import { LeaderboardUser, User } from "@/types";

export const custom_data: User[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    role: "ADMIN",
    createdAt: "2023-01-15T10:30:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    totalPoints: 1000,
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    role: "USER",
    createdAt: "2023-02-20T14:45:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    totalPoints: 800,
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.j@example.com",
    role: "USER",
    createdAt: "2023-03-10T09:15:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    totalPoints: 1200,
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Williams",
    email: "emily.w@example.com",
    role: "USER",
    createdAt: "2023-04-05T11:20:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    totalPoints: 950,
  },
  {
    id: "5",
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@example.com",
    role: "ADMIN",
    createdAt: "2023-01-22T08:45:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    totalPoints: 1500,
  },
  {
    id: "6",
    firstName: "Sarah",
    lastName: "Davis",
    email: "sarah.davis@example.com",
    role: "USER",
    createdAt: "2023-05-12T16:30:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    totalPoints: 750,
  },
  {
    id: "7",
    firstName: "Christopher",
    lastName: "Miller",
    email: "chris.m@example.com",
    role: "USER",
    createdAt: "2023-03-28T13:15:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chris",
    totalPoints: 1100,
  },
  {
    id: "8",
    firstName: "Amanda",
    lastName: "Wilson",
    email: "amanda.w@example.com",
    role: "ADMIN",
    createdAt: "2023-02-14T09:00:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda",
    totalPoints: 1300,
  },
  {
    id: "9",
    firstName: "James",
    lastName: "Taylor",
    email: "james.t@example.com",
    role: "USER",
    createdAt: "2023-06-08T12:45:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    totalPoints: 600,
  },
  {
    id: "10",
    firstName: "Jennifer",
    lastName: "Anderson",
    email: "jennifer.a@example.com",
    role: "USER",
    createdAt: "2023-04-30T15:20:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer",
    totalPoints: 900,
  },
  {
    id: "11",
    firstName: "Robert",
    lastName: "Thomas",
    email: "robert.t@example.com",
    role: "ADMIN",
    createdAt: "2023-01-08T07:30:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    totalPoints: 1700,
  },
  {
    id: "12",
    firstName: "Lisa",
    lastName: "Jackson",
    email: "lisa.j@example.com",
    role: "USER",
    createdAt: "2023-05-25T14:10:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    totalPoints: 850,
  },
  {
    id: "13",
    firstName: "Daniel",
    lastName: "White",
    email: "daniel.white@example.com",
    role: "USER",
    createdAt: "2023-03-15T10:00:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel",
    totalPoints: 1250,
  },
  {
    id: "14",
    firstName: "Michelle",
    lastName: "Harris",
    email: "michelle.h@example.com",
    role: "USER",
    createdAt: "2023-06-18T11:45:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michelle",
    totalPoints: 700,
  },
  {
    id: "15",
    firstName: "Kevin",
    lastName: "Martin",
    email: "kevin.martin@example.com",
    role: "ADMIN",
    createdAt: "2023-02-28T08:15:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin",
    totalPoints: 1400,
  },
  {
    id: "16",
    firstName: "Stephanie",
    lastName: "Thompson",
    email: "stephanie.t@example.com",
    role: "USER",
    createdAt: "2023-04-12T16:50:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Stephanie",
    totalPoints: 950,
  },
  {
    id: "17",
    firstName: "Brian",
    lastName: "Garcia",
    email: "brian.g@example.com",
    role: "USER",
    createdAt: "2023-05-30T13:25:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Brian",
    totalPoints: 1150,
  },
  {
    id: "18",
    firstName: "Rebecca",
    lastName: "Martinez",
    email: "rebecca.m@example.com",
    role: "USER",
    createdAt: "2023-03-05T09:40:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rebecca",
    totalPoints: 780,
  },
  {
    id: "19",
    firstName: "Thomas",
    lastName: "Robinson",
    email: "thomas.r@example.com",
    role: "ADMIN",
    createdAt: "2023-01-25T12:00:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Thomas",
    totalPoints: 1600,
  },
  {
    id: "20",
    firstName: "Nicole",
    lastName: "Clark",
    email: "nicole.clark@example.com",
    role: "USER",
    createdAt: "2023-06-10T15:35:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nicole",
    totalPoints: 880,
  },
  {
    id: "21",
    firstName: "Steven",
    lastName: "Rodriguez",
    email: "steven.r@example.com",
    role: "USER",
    createdAt: "2023-04-22T10:20:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Steven",
    totalPoints: 1020,
  },
  {
    id: "22",
    firstName: "Melissa",
    lastName: "Lewis",
    email: "melissa.lewis@example.com",
    role: "USER",
    createdAt: "2023-05-15T14:55:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Melissa",
    totalPoints: 920,
  },
  {
    id: "23",
    firstName: "Richard",
    lastName: "Lee",
    email: "richard.lee@example.com",
    role: "ADMIN",
    createdAt: "2023-02-10T07:50:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Richard",
    totalPoints: 1350,
  },
];

const sortedData : LeaderboardUser[] = custom_data
  .sort((a, b) => b.totalPoints - a.totalPoints)
  .map((user, index) => ({
    ...user,
    rank: index + 1, // 1-based rank
  }));

export default sortedData;
