interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  role: string;
  createdAt: string;
  avatar: string;
}

export const SampleUsers: User[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    role: "admin",
    createdAt: "2023-01-15T10:30:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    role: "user",
    createdAt: "2023-02-20T14:45:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.j@example.com",
    role: "user",
    createdAt: "2023-03-10T09:15:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Brown",
    email: "emily.brown@example.com",
    role: "editor",
    createdAt: "2023-04-05T16:20:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
  },
  {
    id: "5",
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@example.com",
    role: "user",
    createdAt: "2023-05-12T11:00:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
  },
  {
    id: "6",
    firstName: "Sarah",
    lastName: "Davis",
    email: "sarah.davis@example.com",
    role: "user",
    createdAt: "2023-06-18T13:25:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
  },
  {
    id: "7",
    firstName: "Robert",
    lastName: "Miller",
    email: "robert.m@example.com",
    role: "admin",
    createdAt: "2023-07-22T08:45:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
  },
  {
    id: "8",
    firstName: "Lisa",
    lastName: "Taylor",
    email: "lisa.taylor@example.com",
    role: "editor",
    createdAt: "2023-08-30T15:10:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
  },
  {
    id: "9",
    firstName: "James",
    lastName: "Anderson",
    email: "james.a@example.com",
    role: "user",
    createdAt: "2023-09-14T12:30:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
  },
  {
    id: "10",
    firstName: "Amanda",
    lastName: "Thomas",
    email: "amanda.thomas@example.com",
    role: "user",
    createdAt: "2023-10-08T17:55:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda",
  },
  {
    id: "11",
    firstName: "Christopher",
    lastName: "Lee",
    email: "chris.lee@example.com",
    role: "user",
    createdAt: "2023-11-19T10:05:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Christopher",
  },
  {
    id: "12",
    firstName: "Michelle",
    lastName: "White",
    email: "michelle.white@example.com",
    role: "editor",
    createdAt: "2023-12-03T14:40:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michelle",
  },
  {
    id: "13",
    firstName: "Daniel",
    lastName: "Harris",
    email: "daniel.h@example.com",
    role: "user",
    createdAt: "2024-01-11T09:20:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel",
  },
  {
    id: "14",
    firstName: "Jennifer",
    lastName: "Martin",
    email: "jennifer.m@example.com",
    role: "user",
    createdAt: "2024-02-25T16:15:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer",
  },
  {
    id: "15",
    firstName: "Matthew",
    lastName: "Thompson",
    email: "matt.thompson@example.com",
    role: "admin",
    createdAt: "2024-03-17T11:50:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Matthew",
  },
  {
    id: "16",
    firstName: "Elizabeth",
    lastName: "Garcia",
    email: "elizabeth.g@example.com",
    role: "user",
    createdAt: "2024-04-09T13:35:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elizabeth",
  },
  {
    id: "17",
    firstName: "Kevin",
    lastName: "Martinez",
    email: "kevin.m@example.com",
    role: "user",
    createdAt: "2024-05-21T08:25:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin",
  },
  {
    id: "18",
    firstName: "Stephanie",
    lastName: "Robinson",
    email: "stephanie.r@example.com",
    role: "editor",
    createdAt: "2024-06-07T15:45:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Stephanie",
  },
  {
    id: "19",
    firstName: "Brian",
    lastName: "Clark",
    email: "brian.clark@example.com",
    role: "user",
    createdAt: "2024-07-14T12:10:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Brian",
  },
  {
    id: "20",
    firstName: "Nicole",
    lastName: "Rodriguez",
    email: "nicole.r@example.com",
    role: "user",
    createdAt: "2024-08-29T17:30:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nicole",
  },
];
